// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6DJrQhJqkLj3h5sZ3eqeAjCcZHKkSOc',
    appId: '1:1071675914587:web:a3c8f629d2b603bd09427e',
    messagingSenderId: '1071675914587',
    projectId: 'cajaahorroapp',
    authDomain: 'cajaahorroapp.firebaseapp.com',
    storageBucket: 'cajaahorroapp.firebasestorage.app',
    measurementId: 'G-724DPJ00DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPoxf0AVoGT3fepxrBWsXtCNbiNnrl-s',
    appId: '1:1071675914587:android:3f2f00dcb47028de09427e',
    messagingSenderId: '1071675914587',
    projectId: 'cajaahorroapp',
    storageBucket: 'cajaahorroapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNBCsSKUuHrzyE_di3voEJ8PjGPSUAkH0',
    appId: '1:1071675914587:ios:cf29e22801070fa709427e',
    messagingSenderId: '1071675914587',
    projectId: 'cajaahorroapp',
    storageBucket: 'cajaahorroapp.firebasestorage.app',
    iosBundleId: 'com.example.cajaAhorroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNBCsSKUuHrzyE_di3voEJ8PjGPSUAkH0',
    appId: '1:1071675914587:ios:cf29e22801070fa709427e',
    messagingSenderId: '1071675914587',
    projectId: 'cajaahorroapp',
    storageBucket: 'cajaahorroapp.firebasestorage.app',
    iosBundleId: 'com.example.cajaAhorroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ6DJrQhJqkLj3h5sZ3eqeAjCcZHKkSOc',
    appId: '1:1071675914587:web:f80aee062e2bf2fd09427e',
    messagingSenderId: '1071675914587',
    projectId: 'cajaahorroapp',
    authDomain: 'cajaahorroapp.firebaseapp.com',
    storageBucket: 'cajaahorroapp.firebasestorage.app',
    measurementId: 'G-627WMSPL09',
  );
}
